version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
    restart: always
    volumes:
      - ./:${APP_PATH_CONTAINER}:cached
      - ./docker/nginx/ssl:/etc/nginx/ssl:cached
    ports:
      - 8080:80
      - 443:443
    links:
      - web
    command: ["nginx", "-g", "daemon off;"]

  web:
    build:
      context: ./docker/web
    restart: always
    volumes:
      - ./:${APP_PATH_CONTAINER}:cached
      - ~/.composer/docker-cache/:/root/.composer:cached
    working_dir: ${APP_PATH_CONTAINER}

  node:
    image: node:12.14.1
    tty: true
    volumes:
      - ./:${APP_PATH_CONTAINER}:cached
    working_dir: ${APP_PATH_CONTAINER}
    ports:
      - 3000:80

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql:cached

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8090:80
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db


